services:
  backend:
    build:
      context: ./backend
    container_name: rahti_pro_backend
    ports:
      - "8000:8000"
    environment:
      - DATA_DIR=/code/data
    volumes:
      - ./data:/code/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:8000/api
    container_name: rahti_pro_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
